unbind r
bind r source-file ~/.tmux.conf
set -g mouse on
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
set -g base-index 1

# TMUX Plugin manager setup
set -g @plugin 'rose-pine/tmux'
set -g @plugin 'tmux-plugins/tpm'

set -g @rose_pine_variant 'main'
run '~/.tmux/plugins/tpm/tpm'

# setting ctrl+space as prefix key
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# setting status position top
set-option -g status-position top
